FROM registry.access.redhat.com/ubi8/ruby-27

ENV RAKE_DB_INIT="false" \
    BUNDLER_VERSION='2.2.22' \
    YARN_VERSION='1.22.19' \
    BUNDLE_DIR='./bundle' \
    PUMA_OPTIONS='--config ../etc/puma.cfg'

USER root

# Install yarn
RUN npm install yarn@$YARN_VERSION -g

# Copy the S2I scripts from the specific language image to $STI_SCRIPTS_PATH
COPY ./s2i/bin/ $STI_SCRIPTS_PATH

# Copy extra files to the image.
COPY ./root/ /

# Drop the root user and make the content of /opt/app-root owned by user 1001
RUN chown -R 1001:0 ${APP_ROOT} && chmod -R ug+rwx ${APP_ROOT} && \
    rpm-file-permissions

USER 1001

# Install bundler
RUN gem install bundler -v $BUNDLER_VERSION --no-document && \
    bundle config set --local path $BUNDLE_DIR && \
    bundle config set --local without 'development:test'
