name: build

on:
  push:
    branches: [ main ]

env:
  REPOSITORY: ${{ secrets.REPOSITORY }}
  REPOSITORY_HOST: ${{ secrets.REPOSITORY_HOST }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build-base-container:
    env:
      CONTAINER_IMAGE: base-container
      CONTAINER_VERSION: 1.0.0
      
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: authenticate gcloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
        id: auth

      - name: setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - run: gcloud auth configure-docker $REPOSITORY_HOST
      
      - name: build the base-container
        run: |
          docker build -f base-container/Dockerfile -t "$REPOSITORY_HOST"/"$REPOSITORY"/"$CONTAINER_IMAGE":"$GITHUB_SHA" .
          docker tag $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:$GITHUB_SHA $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:latest
          docker tag $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:$GITHUB_SHA $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:$CONTAINER_VERSION
      
      - name: push the container
        run: |
          docker push $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:$GITHUB_SHA
          docker push $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:latest
          docker push $REPOSITORY_HOST/$REPOSITORY/$CONTAINER_IMAGE:$CONTAINER_VERSION